set(MATRIX_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")
target_sources(${PROJECT_NAME} PUBLIC
FILE_SET CXX_MODULES 
BASE_DIRS ${MATRIX_MODULE_DIR}
FILES
	"${MATRIX_MODULE_DIR}/Matrix.cppm"
	"${MATRIX_MODULE_DIR}/MathMatrix.cppm"
	"${MATRIX_MODULE_DIR}/MatrixHelpers.cppm"
)