set(STD_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")
target_sources(${PROJECT_NAME} PUBLIC
FILE_SET CXX_MODULES
BASE_DIRS ${STD_MODULE_DIR}
FILES
	"${STD_MODULE_DIR}/std.cppm"
	"${STD_MODULE_DIR}/std.compat.cppm"
)
set(CMAKE_CXX_STDLIB_MODULES_JSON "${CMAKE_CURRENT_LIST_DIR}/my.modules.json")