module;

#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <fenv.h>
#include <float.h>
#include <inttypes.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <uchar.h>
#include <wchar.h>
#include <wctype.h>

// <intrin.h> defines some types outside of `extern "C"` or `extern "C++"`.
#include <intrin.h>

// "C++ library headers" [tab:headers.cpp]
#include <algorithm>
#include <array>
#include <atomic>
#include <barrier>
#include <bit>
#include <bitset>
#include <charconv>
#include <chrono>
#include <codecvt>
#include <compare>
#include <complex>
#include <concepts>
#include <condition_variable>
#include <coroutine>
#include <deque>
#include <exception>
#include <execution>
#include <filesystem>
#include <format>
#include <forward_list>
#include <fstream>
#include <functional>
#include <future>
#include <initializer_list>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <latch>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <memory_resource>
#include <mutex>
#include <new>
#include <numbers>
#include <numeric>
#include <optional>
#include <ostream>
#include <queue>
#include <random>
#include <ranges>
#include <ratio>
#include <regex>
#include <scoped_allocator>
#include <semaphore>
#include <set>
#include <shared_mutex>
#include <source_location>
#include <span>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <stop_token>
#include <streambuf>
#include <string>
#include <string_view>
#include <strstream>
#include <syncstream>
#include <system_error>
#include <thread>
#include <tuple>
#include <typeindex>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
#include <version>

#if _HAS_STATIC_RTTI
#include <any>
#endif // _HAS_STATIC_RTTI

#if _HAS_CXX23
#include <expected>
#include <flat_map>
#include <flat_set>
#include <generator>
#include <mdspan>
#include <print>
#include <spanstream>
#include <stacktrace>
#include <stdfloat>
#endif // _HAS_CXX23

// "C++ headers for C library facilities" [tab:headers.cpp.c]
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <cfloat>
#include <cinttypes>
#include <climits>
#include <clocale>
#include <cmath>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuchar>
#include <cwchar>
#include <cwctype>

export module std;

export namespace std {
	#include <type_traits>
	// <cctype>
	using std::isalnum;
	using std::isalpha;
	using std::isblank;
	using std::iscntrl;
	using std::isdigit;
	using std::isgraph;
	using std::islower;
	using std::isprint;
	using std::ispunct;
	using std::isspace;
	using std::isupper;
	using std::isxdigit;
	using std::tolower;
	using std::toupper;

	// <cerrno>
	// Nothing to do, only macros.

	// <cfenv>
	using std::fenv_t;
	using std::fexcept_t;
	using std::feclearexcept;
	using std::fegetexceptflag;
	using std::feraiseexcept;
	using std::fesetexceptflag;
	using std::fetestexcept;
	using std::fegetround;
	using std::fesetround;
	using std::fegetenv;
	using std::feholdexcept;
	using std::fesetenv;
	using std::feupdateenv;

	// <cfloat>
	// Nothing to do, only macros.

	// <cinttypes>
	using std::imaxdiv_t;
	using std::imaxabs;
	using std::imaxdiv;
	using std::strtoimax;
	using std::strtoumax;
	using std::wcstoimax;
	using std::wcstoumax;

	// <climits>
	// Nothing to do, only macros.

	// <clocale>
	using std::lconv;
	using std::setlocale;
	using std::localeconv;

	// <cmath>
	using std::float_t;
	using std::double_t;
	using std::acos;
	using std::acosf;
	using std::acosl;
	using std::asin;
	using std::asinf;
	using std::asinl;
	using std::atan;
	using std::atanf;
	using std::atanl;
	using std::atan2;
	using std::atan2f;
	using std::atan2l;
	using std::cos;
	using std::cosf;
	using std::cosl;
	using std::sin;
	using std::sinf;
	using std::sinl;
	using std::tan;
	using std::tanf;
	using std::tanl;
	using std::acosh;
	using std::acoshf;
	using std::acoshl;
	using std::asinh;
	using std::asinhf;
	using std::asinhl;
	using std::atanh;
	using std::atanhf;
	using std::atanhl;
	using std::cosh;
	using std::coshf;
	using std::coshl;
	using std::sinh;
	using std::sinhf;
	using std::sinhl;
	using std::tanh;
	using std::tanhf;
	using std::tanhl;
	using std::exp;
	using std::expf;
	using std::expl;
	using std::exp2;
	using std::exp2f;
	using std::exp2l;
	using std::expm1;
	using std::expm1f;
	using std::expm1l;
	using std::frexp;
	using std::frexpf;
	using std::frexpl;
	using std::ilogb;
	using std::ilogbf;
	using std::ilogbl;
	using std::ldexp;
	using std::ldexpf;
	using std::ldexpl;
	using std::log;
	using std::logf;
	using std::logl;
	using std::log10;
	using std::log10f;
	using std::log10l;
	using std::log1p;
	using std::log1pf;
	using std::log1pl;
	using std::log2;
	using std::log2f;
	using std::log2l;
	using std::logb;
	using std::logbf;
	using std::logbl;
	using std::modf;
	using std::modff;
	using std::modfl;
	using std::scalbn;
	using std::scalbnf;
	using std::scalbnl;
	using std::scalbln;
	using std::scalblnf;
	using std::scalblnl;
	using std::cbrt;
	using std::cbrtf;
	using std::cbrtl;
	using std::abs;
	using std::fabs;
	using std::fabsf;
	using std::fabsl;
	using std::_Binary_hypot::hypot; // only C's hypot(x, y), not C++'s hypot(x, y, z)
	using std::hypotf;
	using std::hypotl;
	using std::pow;
	using std::powf;
	using std::powl;
	using std::sqrt;
	using std::sqrtf;
	using std::sqrtl;
	using std::erf;
	using std::erff;
	using std::erfl;
	using std::erfc;
	using std::erfcf;
	using std::erfcl;
	using std::lgamma;
	using std::lgammaf;
	using std::lgammal;
	using std::tgamma;
	using std::tgammaf;
	using std::tgammal;
	using std::ceil;
	using std::ceilf;
	using std::ceill;
	using std::floor;
	using std::floorf;
	using std::floorl;
	using std::nearbyint;
	using std::nearbyintf;
	using std::nearbyintl;
	using std::rint;
	using std::rintf;
	using std::rintl;
	using std::lrint;
	using std::lrintf;
	using std::lrintl;
	using std::llrint;
	using std::llrintf;
	using std::llrintl;
	using std::round;
	using std::roundf;
	using std::roundl;
	using std::lround;
	using std::lroundf;
	using std::lroundl;
	using std::llround;
	using std::llroundf;
	using std::llroundl;
	using std::trunc;
	using std::truncf;
	using std::truncl;
	using std::fmod;
	using std::fmodf;
	using std::fmodl;
	using std::remainder;
	using std::remainderf;
	using std::remainderl;
	using std::remquo;
	using std::remquof;
	using std::remquol;
	using std::copysign;
	using std::copysignf;
	using std::copysignl;
	using std::nan;
	using std::nanf;
	using std::nanl;
	using std::nextafter;
	using std::nextafterf;
	using std::nextafterl;
	using std::nexttoward;
	using std::nexttowardf;
	using std::nexttowardl;
	using std::fdim;
	using std::fdimf;
	using std::fdiml;
	using std::fmax;
	using std::fmaxf;
	using std::fmaxl;
	using std::fmin;
	using std::fminf;
	using std::fminl;
	using std::fma;
	using std::fmaf;
	using std::fmal;
	using std::fpclassify;
	using std::isfinite;
	using std::isinf;
	using std::isnan;
	using std::isnormal;
	using std::signbit;
	using std::isgreater;
	using std::isgreaterequal;
	using std::isless;
	using std::islessequal;
	using std::islessgreater;
	using std::isunordered;

	// <csetjmp>
	using std::jmp_buf;
	using std::longjmp;

	// <csignal>
	using std::sig_atomic_t;
	using std::signal;
	using std::raise;

	// <cstdarg>
	using std::va_list;

	// <cstddef>
	using std::ptrdiff_t;
	using std::size_t;
	using std::max_align_t;
	using std::nullptr_t; // added to the C Standard Library in C23

	// <cstdint>
	using std::int8_t;
	using std::int16_t;
	using std::int32_t;
	using std::int64_t;
	using std::int_fast8_t;
	using std::int_fast16_t;
	using std::int_fast32_t;
	using std::int_fast64_t;
	using std::int_least8_t;
	using std::int_least16_t;
	using std::int_least32_t;
	using std::int_least64_t;
	using std::intmax_t;
	using std::intptr_t;
	using std::uint8_t;
	using std::uint16_t;
	using std::uint32_t;
	using std::uint64_t;
	using std::uint_fast8_t;
	using std::uint_fast16_t;
	using std::uint_fast32_t;
	using std::uint_fast64_t;
	using std::uint_least8_t;
	using std::uint_least16_t;
	using std::uint_least32_t;
	using std::uint_least64_t;
	using std::uintmax_t;
	using std::uintptr_t;

	// <cstdio>
	// already exported std::size_t, see <cstddef>
	using std::FILE;
	using std::fpos_t;
	using std::remove;
	using std::rename;
	using std::tmpfile;
	using std::tmpnam;
	using std::fclose;
	using std::fflush;
	using std::fopen;
	using std::freopen;
	using std::setbuf;
	using std::setvbuf;
	using std::fprintf;
	using std::fscanf;
	using std::printf;
	using std::scanf;
	using std::snprintf;
	using std::sprintf;
	using std::sscanf;
	using std::vfprintf;
	using std::vfscanf;
	using std::vprintf;
	using std::vscanf;
	using std::vsnprintf;
	using std::vsprintf;
	using std::vsscanf;
	using std::fgetc;
	using std::fgets;
	using std::fputc;
	using std::fputs;
	using std::getc;
	using std::getchar;
	using std::putc;
	using std::putchar;
	using std::puts;
	using std::ungetc;
	using std::fread;
	using std::fwrite;
	using std::fgetpos;
	using std::fseek;
	using std::fsetpos;
	using std::ftell;
	using std::rewind;
	using std::clearerr;
	using std::feof;
	using std::ferror;
	using std::perror;

	// <cstdlib>
	// already exported std::size_t, see <cstddef>
	using std::div_t;
	using std::ldiv_t;
	using std::lldiv_t;
	using std::abort;
	using std::atexit;
	using std::at_quick_exit;
	using std::exit;
	using std::_Exit;
	using std::quick_exit;
	using std::getenv;
	using std::system;
	using std::calloc;
	using std::free;
	using std::malloc;
	using std::realloc;
	using std::atof;
	using std::atoi;
	using std::atol;
	using std::atoll;
	using std::strtod;
	using std::strtof;
	using std::strtold;
	using std::strtol;
	using std::strtoll;
	using std::strtoul;
	using std::strtoull;
	using std::mblen;
	using std::mbtowc;
	using std::wctomb;
	using std::mbstowcs;
	using std::wcstombs;
	using std::bsearch;
	using std::qsort;
	using std::rand;
	using std::srand;
	// already exported std::abs, see <cmath>
	using std::labs;
	using std::llabs;
	using std::div;
	using std::ldiv;
	using std::lldiv;

	// <cstring>
	// already exported std::size_t, see <cstddef>
	using std::memcpy;
	using std::memmove;
	using std::strcpy;
	using std::strncpy;
	using std::strcat;
	using std::strncat;
	using std::memcmp;
	using std::strcmp;
	using std::strcoll;
	using std::strncmp;
	using std::strxfrm;
	using std::memchr;
	using std::strchr;
	using std::strcspn;
	using std::strpbrk;
	using std::strrchr;
	using std::strspn;
	using std::strstr;
	using std::strtok;
	using std::memset;
	using std::strerror;
	using std::strlen;

	// <ctime>
	// already exported std::size_t, see <cstddef>
	using std::clock_t;
	using std::time_t;
	using std::timespec;
	using std::tm;
	using std::clock;
	using std::difftime;
	using std::mktime;
	using std::time;
	using std::timespec_get;
	using std::asctime;
	using std::ctime;
	using std::gmtime;
	using std::localtime;
	using std::strftime;

	// <cuchar>
	using std::mbstate_t;
	// already exported std::size_t, see <cstddef>
	using std::mbrtoc16;
	using std::c16rtomb;
	using std::mbrtoc32;
	using std::c32rtomb;

	// <cwchar>
	// already exported std::size_t, see <cstddef>
	// already exported std::mbstate_t, see <cuchar>
	using std::wint_t;
	// already exported std::tm, see <ctime>
	using std::fwprintf;
	using std::fwscanf;
	using std::swprintf;
	using std::swscanf;
	using std::vfwprintf;
	using std::vfwscanf;
	using std::vswprintf;
	using std::vswscanf;
	using std::vwprintf;
	using std::vwscanf;
	using std::wprintf;
	using std::wscanf;
	using std::fgetwc;
	using std::fgetws;
	using std::fputwc;
	using std::fputws;
	using std::fwide;
	using std::getwc;
	using std::getwchar;
	using std::putwc;
	using std::putwchar;
	using std::ungetwc;
	using std::wcstod;
	using std::wcstof;
	using std::wcstold;
	using std::wcstol;
	using std::wcstoll;
	using std::wcstoul;
	using std::wcstoull;
	using std::wcscpy;
	using std::wcsncpy;
	using std::wmemcpy;
	using std::wmemmove;
	using std::wcscat;
	using std::wcsncat;
	using std::wcscmp;
	using std::wcscoll;
	using std::wcsncmp;
	using std::wcsxfrm;
	using std::wmemcmp;
	using std::wcschr;
	using std::wcscspn;
	using std::wcspbrk;
	using std::wcsrchr;
	using std::wcsspn;
	using std::wcsstr;
	using std::wcstok;
	using std::wmemchr;
	using std::wcslen;
	using std::wmemset;
	using std::wcsftime;
	using std::btowc;
	using std::wctob;
	using std::mbsinit;
	using std::mbrlen;
	using std::mbrtowc;
	using std::wcrtomb;
	using std::mbsrtowcs;
	using std::wcsrtombs;

	// <cwctype>
	// already exported std::wint_t, see <cwchar>
	using std::wctrans_t;
	using std::wctype_t;
	using std::iswalnum;
	using std::iswalpha;
	using std::iswblank;
	using std::iswcntrl;
	using std::iswdigit;
	using std::iswgraph;
	using std::iswlower;
	using std::iswprint;
	using std::iswpunct;
	using std::iswspace;
	using std::iswupper;
	using std::iswxdigit;
	using std::iswctype;
	using std::wctype;
	using std::towlower;
	using std::towupper;
	using std::towctrans;
	using std::wctrans;
}